# Generated by Django 4.2.30 on 2026-07-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_refund_order_cancellation_reason_order_cancelled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='refund_method',
            field=models.CharField(choices=[('original', 'Original Payment Method'), ('store_credit', 'Store Credit')], default='original', max_length=20),
        ),
    ]
