# Generated by Django 4.2.30 on 2026-07-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_admin_coupon_discount_order_coupon_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
