# Generated by Django 4.2.30 on 2026-07-11 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0010_order_shipping_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='origin',
            field=models.CharField(choices=[('cancellation', 'Order Cancellation'), ('return', 'Return Request'), ('manual', 'Manual / Other')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='refund',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='settlement_note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='refund',
            name='settlement_proof',
            field=models.ImageField(blank=True, null=True, upload_to='refund_proofs/'),
        ),
        migrations.AddField(
            model_name='refund',
            name='settlement_transaction_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
