# Generated by Django 4.2.30 on 2026-07-08 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_merge_20260708_1940'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('source_site', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('never', 'Never synced'), ('ok', 'OK'), ('stock_changed', 'Stock changed'), ('price_changed', 'Price changed'), ('unavailable', 'Source unavailable'), ('removed', 'Product removed'), ('error', 'Error')], default='never', max_length=20)),
                ('last_result', models.CharField(blank=True, max_length=255)),
                ('last_seen_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_seen_stock_status', models.CharField(blank=True, max_length=20)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_product_sources', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='products.product')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='productsource',
            constraint=models.UniqueConstraint(fields=('product', 'url'), name='unique_product_source_url'),
        ),
    ]
