# Generated by Django 6.0.3 on 2026-03-09 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="additional_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="business_category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="business_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="business_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="review_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_seller_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pending", "Pending"),
                    ("suspended", "Suspended"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
