# Generated by Django 4.2.30 on 2026-07-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_superusers_are_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='id_documents/'),
        ),
    ]
