# Generated by Django 6.0.3 on 2026-03-09 17:30

from django.db import migrations, models
import utils.file_upload


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_barcode_product_brand_product_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to=utils.file_upload.product_video_path
            ),
        ),
    ]
