# Generated by Django 4.2.7 on 2026-03-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_productimage_productvideo"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="variants",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
