# Generated by Django 4.2.7 on 2026-03-09 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_category_product_category_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="category_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shops_new",
                to="products.category",
            ),
        ),
    ]
