# Generated by Django 4.2.7 on 2026-03-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_shop_category_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="actualCost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
