# Generated by Django 4.2.30 on 2026-07-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_shop_sender_address_fields'),
        ('products', '0010_add_actual_cost_field'),
    ]

    operations = [
    ]
