# Generated by Django 4.2.30 on 2026-07-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_merge_20260708_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='bank_information',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='shop',
            name='mobile_banking',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shop',
            name='payout_method',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='shop',
            name='setup_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('needs_changes', 'Needs Changes')], default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='tax_information',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shop',
            name='trade_license',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
