# Generated by Django 4.2.30 on 2026-07-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_migrate_legacy_wallets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgeraccount',
            name='account_type',
            field=models.CharField(choices=[('escrow', 'Admin Escrow'), ('platform_balance', 'Platform Balance'), ('wallet_holds', 'Wallet Holds'), ('opening_balance', 'Opening Balance'), ('cod_clearing', 'COD Clearing'), ('customer_wallet', 'Customer Wallet'), ('seller_marketplace', 'Seller Marketplace Balance'), ('seller_locked', 'Seller Locked Balance'), ('seller_paid_out', 'Seller Paid Out'), ('coupon_reserve', 'Admin Coupon Reserve')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='txn_type',
            field=models.CharField(choices=[('online_payment', 'Online Payment'), ('cod_confirmation', 'COD Confirmation'), ('cod_earning', 'COD Earning (delivered)'), ('platform_charge', 'Platform Charge'), ('store_credit_added', 'Store Credit Added'), ('wallet_credit_used', 'Wallet Credit Used'), ('wallet_hold', 'Wallet Hold'), ('wallet_hold_release', 'Wallet Hold Release'), ('refund', 'Refund'), ('withdrawal_requested', 'Withdrawal Requested'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('settlement', 'Settlement'), ('coupon_reserve', 'Coupon Reserve'), ('coupon_release', 'Coupon Release'), ('coupon_redemption', 'Coupon Redemption'), ('manual_adjustment', 'Manual Adjustment'), ('admin_deposit', 'Admin Deposit'), ('seller_deposit', 'Seller Deposit'), ('migration_opening', 'Migrated Opening Balance'), ('reversal', 'Reversal'), ('snapshot_rebuild', 'Snapshot Rebuild')], db_index=True, max_length=30),
        ),
    ]
