# Generated by Django 4.2.7 on 2026-03-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seller", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentmethodsetting",
            old_name="paypal",
            new_name="bkash",
        ),
        migrations.RemoveField(
            model_name="paymentmethodsetting",
            name="bank_transfer",
        ),
        migrations.AddField(
            model_name="paymentmethodsetting",
            name="nagad",
            field=models.BooleanField(default=True),
        ),
    ]
