# Generated by Django 4.2.7 on 2026-03-10 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_shop_category_fk"),
        ("seller", "0002_rename_paypal_paymentmethodsetting_bkash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Required when coupon_type is 'category'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="seller.category",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="coupon_type",
            field=models.CharField(
                choices=[
                    ("all_products", "All Products"),
                    ("specific_products", "Specific Products"),
                    ("category", "Category"),
                    ("first_order", "First Order Only"),
                ],
                default="all_products",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="min_order_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Minimum order amount to apply coupon",
                max_digits=10,
            ),
        ),
        migrations.CreateModel(
            name="CouponProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_products",
                        to="seller.coupon",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("coupon", "product")},
            },
        ),
    ]
