# Generated by Django 4.2.30 on 2026-07-11 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_update_coupon_category_references'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
