# Generated by Django 4.2.30 on 2026-07-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='saved_for_later',
            field=models.BooleanField(default=False),
        ),
    ]
